services:
  - type: web
    name: guardian-backend
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: guardian-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://guardian-dashboard.onrender.com

databases:
  - name: guardian-db
